### ISSUE TITLE
Cleanup: Pave the way for 0.0.1

### ISSUE THREAD

**Issue by robrobbins** [computablelabs/contracts#25]
Similar to the cleanup that just occurred in `computable.js`, clear out the old alpha code and move in some new alpha code. This time, move in the bare minimum contracts to setup a data-market TCR. Likely https://github.com/skmgoldin/tcr

Also omit the large amount of javascript code here that is supporting the js-testing env as that is now located in `computable.js`. 

Include linting an first via solium, and assure that's wired to travis. Aside from that leave the repo as bare-bones as possible as we ramp-up our .sol staffing.

In follow up tickets I think we can look at pulling in some best-of-breed tools for analysis like mythril (or other...)

**Comment by rbharath** [comment]
Big fan of adding Mythril type tooling for analysis!
